function createhgtransform(Parent1, Vertices1, Faces1, Vertices2)
%CREATEHGTRANSFORM(Parent1, Vertices1, Faces1, Vertices2)
%  PARENT1:  hgtransform parent
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  VERTICES2:  patch vertices

%  Auto-generated by MATLAB on 09-Jan-2025 12:02:37

% Create hgtransform
hgtransform('HitTest','on','Visible','on','Parent',Parent1);

% Create patch
patch('FaceAlpha',0.6,'Vertices',Vertices1,'LineWidth',1,'Faces',Faces1,...
    'EdgeColor','none');

% Create text
text('VerticalAlignment','baseline','HorizontalAlignment','center',...
    'FontSize',18,...
    'Interpreter','latex',...
    'String','\rm{\textbf{150 $\mu$m}}',...
    'Position',[100 -635 0],...
    'Color',[1 1 1]);

% Create patch
patch('Vertices',Vertices2,'Faces',Faces1,'FaceColor',[1 1 1]);

